### PR TITLE
Minor cleanups for Java exercise and solutions

### PR DESCRIPTION
**Pull request by codecop**
Luca, thanks for the great exercise.

Working through the Java part I did some minor cleanups, e.g. adding ignores, formatting source - as well as removing unwanted files from the provided solutions, e.g. deleting compiled class files and Maven test results.

I also made all markdown links relative which is supported by Github since some time. So clones stay inside themselves when navigating.

### CODE REVIEW

**Comment by merezano** [comment]
Some of these changes are tool-specific (e.g., assuming Maven is being used).

**Comment by codecop** [comment]
Interesting point. As Maven pom's were provided, it seemed like the current choice. It is difficult to provide for all tools, e.g. add Eclipse, IDEA and Netbeans configurations, but all these tools are able to import Maven projects, in order to make it easier for ppl to get started. All Java projects I know have 1) Eclipse/IDEA in ignore and 2) do not commit the files of these tools.
But if you like I can separate these changes to a branch.

**Comment by lucaminudel** [comment]
Hi codecop

when people uses this code off-line, without an internet connection, a copy of commons-lang3-3.1.jar is needed.

Would be great if you could rollback that commit so I can merge your pull request.

Luca

**Comment by codecop** [comment]
Luca,
thanks for looking at my changes. I removed the first commit, which deleted the commons-lang.jar as you asked.

**Comment by lucaminudel** [comment]
Peter / codecop, pull request merged, thanks !

Luca

**Pull request merged**
